# -*- coding: utf-8 -*-
"""Telco_Despliegue_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wGwKiHuUF3-9FdDTVES6S68G1UpkN9ZS

# Despliegue

# Cargamos el modelo
# Cargamos los datos futuros
# Preparar los datos futuros
# Aplicamos el modelo para la predicción
"""

#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

#Cargamos el modelo
import pickle
filename = 'pipeline_telco_churn_final.pkl'
model, variables, min_max_scaler, labelencoder = pickle.load(open(filename, 'rb'))

"""#Cargamos el modelo"""

#Cargamos los datos futuros (opcional)
# data = pd.read_csv("telco-datosFuturos.csv")
# data.head()

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de Churn - Telco (Red Neuronal)')

# Controles de entrada
SeniorCitizen = st.selectbox('SeniorCitizen', [0, 1], index=0)
tenure = st.slider('tenure', min_value=0, max_value=100, value=12, step=1)
InternetService = st.selectbox('InternetService', ['DSL', 'Fiber optic', 'No'])
Contract = st.selectbox('Contract', ['Month-to-month', 'One year', 'Two year'])
PaperlessBilling = st.selectbox('PaperlessBilling', ['Yes', 'No'])
OnlineSecurity = st.selectbox('OnlineSecurity', ['Yes', 'No', 'No internet service'])
OnlineBackup = st.selectbox('OnlineBackup', ['Yes', 'No', 'No internet service'])
DeviceProtection = st.selectbox('DeviceProtection', ['Yes', 'No', 'No internet service'])
TechSupport = st.selectbox('TechSupport', ['Yes', 'No', 'No internet service'])
StreamingTV = st.selectbox('StreamingTV', ['Yes', 'No', 'No internet service'])
StreamingMovies = st.selectbox('StreamingMovies', ['Yes', 'No', 'No internet service'])
PaymentMethod = st.selectbox('PaymentMethod', [
    'Electronic check', 'Mailed check',
    'Bank transfer (automatic)', 'Credit card (automatic)'
])

#Dataframe de entrada (mismos nombres de variables de origen)
datos = [[SeniorCitizen, tenure, InternetService, OnlineSecurity, OnlineBackup,
          DeviceProtection, TechSupport, StreamingTV, StreamingMovies,
          Contract, PaperlessBilling, PaymentMethod]]

data = pd.DataFrame(datos, columns=[
    'SeniorCitizen','tenure','InternetService','OnlineSecurity','OnlineBackup',
    'DeviceProtection','TechSupport','StreamingTV','StreamingMovies',
    'Contract','PaperlessBilling','PaymentMethod'
])

data

#Se realiza la preparación debe ser igual al aprendizaje
# Dummies con drop_first=True para algunas, y completas para el resto

data_preparada = data.copy()

# Dummies con drop_first=True
data_preparada = pd.get_dummies(
    data_preparada,
    columns=[c for c in ['SeniorCitizen', 'Dependents', 'PaperlessBilling'] if c in data_preparada.columns],
    drop_first=True,
    dtype=int
)

# Dummies completas (drop_first=False)
data_preparada = pd.get_dummies(
    data_preparada,
    columns=[c for c in ['InternetService','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','Contract','PaymentMethod'] if c in data_preparada.columns],
    drop_first=False,
    dtype=int
)

data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada = data_preparada.reindex(columns=variables, fill_value=0)
data_preparada.head()

#Normalización para los métodos que lo requieren (RN)
# En los despliegues no se llama fit
if 'tenure' in data_preparada.columns:
    data_preparada[['tenure']] = min_max_scaler.transform(data_preparada[['tenure']])

data_preparada.head()

"""# Predicciones"""

#Hacemos la predicción con la Red Neuronal
Y_pred = model.predict(data_preparada)
print(Y_pred)


# Etiquetas originales con LabelEncoder
y_labels = labelencoder.inverse_transform(Y_pred)
print('Pred (No/Yes):', y_labels)
